### ISSUE TITLE
New members do not get email to create account

### ISSUE THREAD

**Issue by grkatsas** [sass-team/sass-app#105]
A number of new hires did not get emails to create account so they can receive notifications of appointments.

**Comment by rdok** [comment]
@grkatsas thanks for the issue request. I'll check on this on the evening. It seems the system is not sending any emails, I think.

**Comment by rdok** [comment]
@grkatsas as a temporary solution,  you could probably set them their password from the admin panel, if I remember correctly?

**Comment by rdok** [comment]
@grkatsas OK so this issue does relate to our sass source code - [Relevant verification](https://github.com/sass-team/sass-app/blob/v1.0.4/tests/Unit/Mails/RecoverMailTest.php#L21). 

Which leads me to believe it has something to do with our server. So I opened a ticket with our server provider. They will respond in the next 24 hours. 

In the meantime, we could temporary allow an admin/secreteriat to the set the password for new users?  How does that sound?

**Comment by rdok** [comment]
Closed by https://github.com/sass-team/sass-app/commit/f3ad63e2553066e601b676cf8370165a86dcd9ec  

Our server provider suggests we're find from the server settings. 

As such, I just implemented this functionality to use our local mail server instead of the mailgun api. 

Please let me know if any issue arises.
